// VibeSane deterministic coverage fixtures. Every value is fake/non-functional.
const JWT_SECRET = "FAKE_JWT_SECRET_FOR_VIBESANE_TEST_12345";
const GOOGLE_KEY = "AIzaSyDUMMYVIBESANETESTKEY000000000000000";
const GITHUB_PAT = "ghp_FAKEVIBESANETESTTOKEN0000000000000000";
const PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----";
const DB_URL = "postgres://fakeuser:fakepassword@example.invalid:5432/test";
const password = "fake-password-for-vibesane-test";
const auth = "Bearer FAKE_BEARER_TOKEN_123456789012345";
const SENDGRID = "SG.fakefakefakefakefake.fakefakefakefakefake";
const TWILIO_AUTH_TOKEN = "FAKETWILIOTOKEN1234567890123456";
const SLACK = "xoxb-fake-vibesane-test-token-123456";
const NPM = "npm_FAKEVIBESANETESTTOKEN1234567890";
const VERCEL_TOKEN = "FAKEVERCELTOKEN123456789012345";
const NETLIFY_AUTH_TOKEN = "FAKENETLIFYTOKEN123456789012345";

const child_process = require("child_process");
child_process.exec(userInput);
eval(userInput);
const dynamic = new Function(userInput);
element.innerHTML = userInput;
const dangerous = { dangerouslySetInnerHTML: { __html: userInput } };
document.write(userInput);
window.postMessage({ secret: auth }, "*");
res.redirect(req.query.next);
const cors = { "Access-Control-Allow-Origin": "*" };
res.cookie("session", auth, { secure: false, sameSite: "none" });
res.cookie("session2", auth, {});
const insecure = "http://example.invalid/api";
const debug = "/debug";
const admin = "/admin";
const internal = "/internal/status";

const weak = require("crypto").createHash("md5");
const weak2 = require("crypto").createHash("sha1");
const token = Math.random();
fs.readFile(req.query.file);
fs.writeFile(req.body.path, data);
exec(req.query.command);
const pkg = require("pickle");
pkg.unserialize(req.body.data);
const hash = passwordHashMd5(password);
const ENCRYPTION_KEY = "FAKE_ENCRYPTION_KEY_1234567890123456";
const joined = path.resolve(req.query.path);
fetch(req.query.url);
const polluted = JSON.parse(req.body.json); polluted.__proto__.isAdmin = true;
const tlsOptions = { rejectUnauthorized: false };
const insecureTls = { verify: false };
const publicFile = fs.readFileSync(req.query.path);
const url = req.body.callback;
